import { NextResponse } from "next/server";

import { createSupabaseAdminClient } from "@flowlab/auth";
import { prisma } from "@flowlab/db";
import { getPlatformSession } from "../../../../../../../lib/session";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await getPlatformSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (session.role !== "superadmin") return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { id: tenantId } = await params;
  const body = (await request.json().catch(() => null)) as { userId?: string } | null;
  const userId = body?.userId;
  if (!userId) return NextResponse.json({ error: "userId required" }, { status: 400 });

  const user = await prisma.tenantUser.findFirst({
    where: { id: userId, tenantId },
    include: { tenant: { include: { profile: true } } }
  });
  if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });
  if (!user.authUserId) {
    return NextResponse.json(
      { error: "This user has not been migrated to Supabase Auth yet. Ask them to sign in once first." },
      { status: 400 }
    );
  }

  const admin = createSupabaseAdminClient();
  const { data, error } = await admin.auth.admin.generateLink({
    type: "recovery",
    email: user.email,
    options: {
      redirectTo:
        process.env.NODE_ENV === "production"
          ? `https://${user.tenant.slug}.flowlabsolutions.au/login`
          : `http://${user.tenant.slug}.localhost:3001/login`
    }
  });

  if (error || !data.properties?.action_link) {
    return NextResponse.json({ error: error?.message ?? "Could not generate reset link" }, { status: 500 });
  }

  await prisma.platformEventLog.create({
    data: {
      tenantId,
      eventType: "info",
      service: "worker",
      direction: "inbound",
      status: "success",
      requestSummary: "Password reset link generated by superadmin",
      responseSummary: `Admin ${session.email} generated reset link for ${user.email}`,
      triggeredBy: `superadmin_${session.email}`
    }
  });

  return NextResponse.json({
    ok: true,
    email: user.email,
    actionLink: data.properties.action_link
  });
}
